function S1F111Jan2018155716 = importCSVfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   S1F111JAN2018155716 = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   S1F111JAN2018155716 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   S1F111Jan2018155716 = importfile('S1_F1_11-Jan-2018_15-57-16.csv', 1, 400);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/01/25 15:17:22

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2; %az od druhe radky, v prvni jsou nazvy sloupcu
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,11,12,14,16,17]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,3,4,5,6,7,8,9,11,12,14,16,17]);
rawCellColumns = raw(:, [10,13,15,18]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
S1F111Jan2018155716 = table;
S1F111Jan2018155716.RedX = cell2mat(rawNumericColumns(:, 1));
S1F111Jan2018155716.RedY = cell2mat(rawNumericColumns(:, 2));
S1F111Jan2018155716.RedZ = cell2mat(rawNumericColumns(:, 3));
S1F111Jan2018155716.WhiteX = cell2mat(rawNumericColumns(:, 4));
S1F111Jan2018155716.WhiteY = cell2mat(rawNumericColumns(:, 5));
S1F111Jan2018155716.WhiteZ = cell2mat(rawNumericColumns(:, 6));
S1F111Jan2018155716.CameraPitch = cell2mat(rawNumericColumns(:, 7));
S1F111Jan2018155716.CameraRoll = cell2mat(rawNumericColumns(:, 8));
S1F111Jan2018155716.CameraYaw = cell2mat(rawNumericColumns(:, 9));
S1F111Jan2018155716.Response = rawCellColumns(:, 1);
S1F111Jan2018155716.RTms = cell2mat(rawNumericColumns(:, 10));
S1F111Jan2018155716.StimOnsetClock = cell2mat(rawNumericColumns(:, 11));
S1F111Jan2018155716.Name = rawCellColumns(:, 2);
S1F111Jan2018155716.IsCorrect = cell2mat(rawNumericColumns(:, 12));
S1F111Jan2018155716.BlockAnswer = rawCellColumns(:, 3);
S1F111Jan2018155716.Missed = cell2mat(rawNumericColumns(:, 13));
S1F111Jan2018155716.ResponseOnsetClock = cell2mat(rawNumericColumns(:, 14));
S1F111Jan2018155716.TaskType = rawCellColumns(:, 4);

